"""
Shared helpers for the AR-model visibility-graph experiments
(Adjacent_AR_test.py, useful_randomthing_about_graph_AR_length.py),
exploring the degree-distribution properties discussed in the report's
Section 1.3 ("Process of research"): for a time series generated by an
AR model, how does its visibility graph's degree distribution behave?

Both consumer scripts previously duplicated this exact logic (a
GraphVisualization class, a triple-nested-loop visibility() check, and
a get_freq_dist() helper) -- factored out here, and the visibility
check itself now reuses visibility_graph.natural_visibility_graph
(O(n^2), verified against a brute-force check of the definition)
instead of reimplementing the O(n^3) triple loop a third time.
"""
import networkx as nx
import numpy as np

from visibility_graph import edge_weights_euclidean, natural_visibility_graph

# Placeholder AR coefficients -- the original scripts loaded these from
# parameter.xlsx, which isn't included in this repo. This is a stable
# AR(4) example so the scripts run standalone; swap in your own
# coefficients (or reintroduce the Excel loading) once you have them.
DEFAULT_AR_COEFFS = [0.5, -0.2, 0.1, -0.05]


def generate_ar_series(coeffs, num_steps, rng=None):
    """Simulate an AR(p) series: y[i] = sum_j coeffs[j] * y[i-j-1] + noise[i]."""
    rng = rng or np.random.default_rng()
    porder = len(coeffs)
    noise = rng.standard_normal(num_steps)
    y = np.zeros(num_steps)
    for i in range(porder, num_steps):
        for j in range(porder):
            y[i] += coeffs[j] * y[i - j - 1]
        y[i] += noise[i]
    return y


def visibility_graph_with_weights(y):
    """Natural visibility graph of y, with each edge's Euclidean
    distance (in (index, value) space) stored as its "weight" attribute."""
    t = np.arange(len(y), dtype=float)
    G = natural_visibility_graph(t, y)
    nx.set_edge_attributes(G, edge_weights_euclidean(G, t, y), "weight")
    return G


def degree_sequence(G):
    """Node degree in node-index order 0..n-1, as a numpy array."""
    deg = np.zeros(G.number_of_nodes())
    for node, d in G.degree():
        deg[node] = d
    return deg


def freq_dist(values):
    """Frequency count of each rounded integer value in `values` --
    e.g. how many nodes have degree 0, 1, 2, ..."""
    max_val = int(round(max(values)))
    freq = np.zeros(max_val + 1)
    for v in values:
        freq[int(round(v))] += 1
    return freq


def draw_circular(G, node_color):
    """Circular-layout plot of G, edge width inversely related to the
    time-index distance between its endpoints (thicker = closer in
    time) -- matches the original scripts' visualization."""
    edgewidths = [1.0 / np.sqrt(abs(u - v)) for u, v in G.edges()]
    nx.draw_circular(G, node_color=node_color, width=edgewidths, with_labels=True)
